# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlDatabase, QSqlTableModel, QSqlQueryModel, QSqlQuery
from PyQt5.QtWidgets import QApplication, QMainWindow, QAction, qApp, QAbstractItemView

from common.constants import CLIENT_DB_PREFIX


class Ui_MainWindow(QMainWindow):
    def __init__(self, username):
        self.user = username
        self.conn = QSqlDatabase.addDatabase('QSQLITE')
        self.conn.setDatabaseName(f'{CLIENT_DB_PREFIX}_{self.user}.db3')
        self.conn.open()
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.setFixedSize(800, 600)

        self.contactListView = QtWidgets.QTableView(self)
        self.contactListView.setGeometry(QtCore.QRect(10, 40, 256, 451))
        self.contactListView.setObjectName("contactListWidget")
        self.contactListView.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.show_contact_list()
        self.contactListView.doubleClicked.connect(self.show_message_history)

        self.historyView = QtWidgets.QTableView(self)
        self.historyView.setGeometry(QtCore.QRect(270, 40, 521, 451))
        self.historyView.setObjectName("tableWidget")
        self.bind_message_history()

        self.textEdit = QtWidgets.QTextEdit(self)
        self.textEdit.setGeometry(QtCore.QRect(270, 495, 461, 64))
        self.textEdit.setObjectName("textEdit")

        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(740, 500, 55, 45))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 510, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(self)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 510, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(20, 25, 81, 16))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(280, 25, 61, 16))
        self.label_2.setObjectName("label_2")

        exitAction = QAction('Exit', self)
        exitAction.setShortcut('Ctrl+Q')
        exitAction.triggered.connect(qApp.quit)

        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menubar.addAction(exitAction)
        self.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Messenger client"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.pushButton_2.setText(_translate("MainWindow", "Add contact"))
        self.pushButton_3.setText(_translate("MainWindow", "Remove contact"))
        self.label.setText(_translate("MainWindow", "Contact List"))
        self.label_2.setText(_translate("MainWindow", "Messages"))

    def show_contact_list(self):
        model = QSqlTableModel(parent=self)
        model.setTable('contacts')
        model.setSort(1, QtCore.Qt.AscendingOrder)
        model.select()

        self.contactListView.setModel(model)

        self.contactListView.hideColumn(0)
        self.contactListView.setColumnWidth(1, 250)
        self.contactListView.verticalHeader().setVisible(False)
        self.contactListView.horizontalHeader().setVisible(False)

    def bind_message_history(self):
        self.history = QSqlQueryModel(parent=self)
        self.historyView.setModel(self.history)

    def show_message_history(self):
        target = self.contactListView.currentIndex().data()
        query = QSqlQuery()
        query.prepare('SELECT '
                      'date(date_time) as date,'
                      'time(date_time) as time,'
                      'target,'
                      'content, '
                      'outgoing '
                      'FROM message_history '
                      'WHERE target = :target '
                      'ORDER BY date_time')
        query.bindValue(':target', target)
        query.exec_()
        self.history.setQuery(query)
        self.historyView.resizeColumnsToContents()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    test = Ui_MainWindow('user0')
    test.statusBar().showMessage('Connected to TEST realm')
    app.exec_()
